package main

import (
	"image"
	"image/color"
	"image/png"
	"os"
)

// Pic generates a 2D image using a mathematical function.
func Pic(dx, dy int) [][]uint8 {
	image := make([][]uint8, dy)
	for s := range image {
		image[s] = make([]uint8, dx)
		for e := range image[s] {
			image[s][e] = uint8(s * e) // Mathematical function: s * e
		}
	}
	return image
}

// createImage creates an image from the Pic function and saves it as a PNG file.
func createImage(dx, dy int, filename string) {
	// Create a new grayscale image of size dx x dy
	img := image.NewGray(image.Rect(0, 0, dx, dy))

	// Fill the image with values generated by Pic
	picData := Pic(dx, dy)
	for y := 0; y < dy; y++ {
		for x := 0; x < dx; x++ {
			// Use color.Gray to set the pixel color
			img.Set(x, y, color.Gray{Y: picData[y][x]})
		}
	}

	// Save the image to a PNG file
	file, err := os.Create(filename)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	err = png.Encode(file, img)
	if err != nil {
		panic(err)
	}
}

func main() {
	// Define the image size
	dx, dy := 256, 256

	// Create and save the image
	createImage(dx, dy, "output.png")
	println("Image generated and saved to output.png")
}
